name=SPI
version=1.0
author=Arduino
maintainer=Arduino <info@arduino.cc>
modifier=mgndler2
sentence=Module for PluggableUSB infrastructure. Exposes an API for devices like Keyboards, Mice and Gamepads. 
paragraph=
category=Communication
url=
architectures=wch
